CREATE OR REPLACE TABLE CUSTOMER(
   CUSTOMERID     VARCHAR(10) NOT NULL PRIMARY KEY
  ,CUSTOMERTYPEID VARCHAR(2) NOT NULL
  ,COUNTRY        VARCHAR(2) NOT NULL
  ,LANGUAGE       VARCHAR(2) NOT NULL
  ,CREATEDBY      INTEGER  NOT NULL
  ,CREATEDAT      DATE  NOT NULL
  ,CHANGEDBY      INTEGER  NOT NULL
  ,CHANGEDAT      DATE  NOT NULL
);

CREATE OR REPLACE TABLE CUSTOMERSHIERARCHY(
   HIERARCHYID VARCHAR(10) NOT NULL PRIMARY KEY
  ,DESCRIPTION VARCHAR(22) NOT NULL
  ,LEVEL       VARCHAR(6) NOT NULL
);

CREATE OR REPLACE TABLE CUSTOMERTEXTS(
   CUSTOMERID   VARCHAR(10) NOT NULL PRIMARY KEY
  ,LANGUAGE     VARCHAR(2) NOT NULL
  ,SHORT_DESCR  VARCHAR(30)
  ,MEDIUM_DESCR VARCHAR(22) NOT NULL
  ,LONG_DESCR   VARCHAR(30)
);

CREATE OR REPLACE TABLE CUSTOMERTYPE(
   CUSTOMERTYPEID VARCHAR(2) NOT NULL PRIMARY KEY
  ,LANGUAGE       VARCHAR(2) NOT NULL
  ,CREATEDBY      INTEGER  NOT NULL
  ,CREATEDAT      DATE  NOT NULL
  ,CHANGEDBY      INTEGER  NOT NULL
  ,CHANGEDAT      DATE  NOT NULL
);

CREATE OR REPLACE TABLE CUSTOMERTYPETEXTS(
   CUSTOMERTYPEID VARCHAR(2) NOT NULL PRIMARY KEY
  ,LANGUAGE       VARCHAR(2) NOT NULL
  ,SHORT_DESCR    VARCHAR(2) NOT NULL
  ,MEDIUM_DESCR   VARCHAR(10) NOT NULL
  ,LONG_DESCR     VARCHAR(30)
);

CREATE OR REPLACE TABLE FINANCIALTRANSACTIONS(
   TRANSACTIONID     INTEGER  NOT NULL PRIMARY KEY 
  ,ACCOUNTID         VARCHAR(8) NOT NULL
  ,ACCOUNTTYPEID     VARCHAR(3) NOT NULL
  ,CUSTOMERID        VARCHAR(10) NOT NULL
  ,CUSTOMERTYPEID    VARCHAR(2) NOT NULL
  ,PRODUCTID         VARCHAR(10) NOT NULL
  ,PRODUCTCATEGORYID VARCHAR(2) NOT NULL
  ,PROFITCENTERID    VARCHAR(10) NOT NULL
  ,VERSION           VARCHAR(6) NOT NULL
  ,DATE              DATE  NOT NULL
  ,VALUE             VARCHAR(12) NOT NULL
);

CREATE OR REPLACE TABLE GLACCOUNTS(
   ACCOUNTID     VARCHAR(8) NOT NULL PRIMARY KEY
  ,ACCOUNTTYPEID VARCHAR(3) NOT NULL
  ,LANGUAGE      VARCHAR(2) NOT NULL
  ,CREATEDBY     INTEGER  NOT NULL
  ,CREATEDAT     DATE  NOT NULL
  ,CHANGEDBY     INTEGER  NOT NULL
  ,CHANGEDAT     DATE  NOT NULL
);

CREATE OR REPLACE TABLE GLACCOUNTSHIERARCHY(
   HIERARCHYID VARCHAR(8) NOT NULL PRIMARY KEY
  ,DESCRIPTION VARCHAR(41) NOT NULL
  ,LEVEL       VARCHAR(8) NOT NULL
);

CREATE OR REPLACE TABLE GLACCOUNTSTEXTS(
   ACCOUNTID    VARCHAR(8) NOT NULL PRIMARY KEY
  ,LANGUAGE     VARCHAR(2) NOT NULL
  ,SHORT_DESCR  VARCHAR(30)
  ,MEDIUM_DESCR VARCHAR(41) NOT NULL
  ,LONG_DESCR   VARCHAR(30)
);

CREATE OR REPLACE TABLE GLACCOUNTTYPE(
   ACCOUNTTYPEID VARCHAR(4) NOT NULL PRIMARY KEY
  ,LANGUAGE      VARCHAR(2) NOT NULL
  ,CREATEDBY     INTEGER  NOT NULL
  ,CREATEDAT     DATE  NOT NULL
  ,CHANGEDBY     INTEGER  NOT NULL
  ,CHANGEDAT     DATE  NOT NULL
);

CREATE OR REPLACE TABLE GLACCOUNTTYPETEXTS(
   ACCOUNTTYPEID VARCHAR(4) NOT NULL PRIMARY KEY
  ,LANGUAGE      VARCHAR(2) NOT NULL
  ,SHORT_DESCR   VARCHAR(30)
  ,MEDIUM_DESCR  VARCHAR(22) NOT NULL
  ,LONG_DESCR    VARCHAR(30)
);

CREATE OR REPLACE TABLE PRODUCTCATEGORIES(
   PRODCATEGORYID VARCHAR(2) NOT NULL PRIMARY KEY
  ,LANGUAGE       VARCHAR(2) NOT NULL
  ,CREATEDBY      INTEGER  NOT NULL
  ,CREATEDAT      DATE  NOT NULL
  ,CHANGEDBY      INTEGER  NOT NULL
  ,CHANGEDAT      DATE  NOT NULL
);

CREATE OR REPLACE TABLE PRODUCTCATEGORYTEXTS(
   PRODCATEGORYID VARCHAR(2) NOT NULL PRIMARY KEY
  ,LANGUAGE       VARCHAR(2) NOT NULL
  ,SHORT_DESCR    VARCHAR(17) NOT NULL
  ,MEDIUM_DESCR   VARCHAR(30)
  ,LONG_DESCR     VARCHAR(30)
);

CREATE OR REPLACE TABLE PRODUCTHIERARCHY(
   HIERARCHYID VARCHAR(10) NOT NULL PRIMARY KEY
  ,DESCRIPTION VARCHAR(23) NOT NULL
  ,LEVEL       VARCHAR(7) NOT NULL
);

CREATE OR REPLACE TABLE PRODUCTS(
   PRODUCTID          VARCHAR(10) NOT NULL PRIMARY KEY
  ,TYPECODE           VARCHAR(2) NOT NULL
  ,PRODUCTCATEGORYID  VARCHAR(2) NOT NULL
  ,LANGUAGE           VARCHAR(2) NOT NULL
  ,SUPPLIER_PARTNERID INTEGER  NOT NULL
  ,TAXTARIFFCODE      BOOLEAN  NOT NULL
  ,QUANTITYUNIT       VARCHAR(2) NOT NULL
  ,WEIGHTMEASURE      INTEGER  NOT NULL
  ,WEIGHTUNIT         VARCHAR(2) NOT NULL
  ,CURRENCY           VARCHAR(3) NOT NULL
  ,PRICE              NUMERIC(7,2) NOT NULL
  ,WIDTH              NUMERIC(5,3) NOT NULL
  ,DEPTH              NUMERIC(5,3) NOT NULL
  ,HEIGHT             NUMERIC(5,3) NOT NULL
  ,DIMENSIONUNIT      VARCHAR(30)
  ,CREATEDBY          INTEGER  NOT NULL
  ,CREATEDAT          DATE  NOT NULL
  ,CHANGEDBY          INTEGER  NOT NULL
  ,CHANGEDAT          DATE  NOT NULL
  ,PRODUCTPICURL      VARCHAR(30)
);

CREATE OR REPLACE TABLE PRODUCTTEXTS(
   PRODUCTID    VARCHAR(10) NOT NULL PRIMARY KEY
  ,LANGUAGE     VARCHAR(2) NOT NULL
  ,SHORT_DESCR  VARCHAR(16) NOT NULL
  ,MEDIUM_DESCR VARCHAR(23) NOT NULL
  ,LONG_DESCR   VARCHAR(30)
);

CREATE OR REPLACE TABLE PROFITCENTER(
   PROFITCENTERID VARCHAR(10) NOT NULL PRIMARY KEY
  ,LANGUAGE       VARCHAR(2) NOT NULL
  ,CREATEDBY      INTEGER  NOT NULL
  ,CREATEDAT      DATE  NOT NULL
  ,CHANGEDBY      INTEGER  NOT NULL
  ,CHANGEDAT      DATE  NOT NULL
);

CREATE OR REPLACE TABLE PROFITCENTERHIERARCHY(
   HIERARCHYID VARCHAR(28) NOT NULL PRIMARY KEY
  ,DESCRIPTION VARCHAR(28) NOT NULL
  ,LEVEL       VARCHAR(28) NOT NULL
);

CREATE OR REPLACE TABLE PROFITCENTERTEXTS(
   PROFITCENTERID VARCHAR(10) NOT NULL PRIMARY KEY
  ,LANGUAGE       VARCHAR(2) NOT NULL
  ,SHORT_DESCR    VARCHAR(15) NOT NULL
  ,MEDIUM_DESCR   VARCHAR(25) NOT NULL
  ,LONG_DESCR     VARCHAR(28) NOT NULL
);
