CREATE OR REPLACE TABLE BusinessPartners(
   PARTNERID    INTEGER  NOT NULL PRIMARY KEY 
  ,PARTNERROLE  INTEGER  NOT NULL
  ,EMAILADDRESS VARCHAR(39) NOT NULL
  ,PHONENUMBER  INTEGER  NOT NULL
  ,FAXNUMBER    VARCHAR(30)
  ,WEBADDRESS   VARCHAR(35) NOT NULL
  ,ADDRESSID    INTEGER  NOT NULL
  ,COMPANYNAME  VARCHAR(21) NOT NULL
  ,LEGALFORM    VARCHAR(8) NOT NULL
  ,CREATEDBY    INTEGER  NOT NULL
  ,CREATEDAT    DATE  NOT NULL
  ,CHANGEDBY    INTEGER  NOT NULL
  ,CHANGEDAT    DATE  NOT NULL
  ,CURRENCY     VARCHAR(3) NOT NULL
);

CREATE OR REPLACE TABLE SalesOrderItems(
   SALESORDERID   INTEGER  NOT NULL PRIMARY KEY 
  ,SALESORDERITEM INTEGER  NOT NULL
  ,PRODUCTID      VARCHAR(10) NOT NULL
  ,NOTEID         VARCHAR(30)
  ,CURRENCY       VARCHAR(3) NOT NULL
  ,GROSSAMOUNT    INTEGER  NOT NULL
  ,NETAMOUNT      VARCHAR(7) NOT NULL
  ,TAXAMOUNT      VARCHAR(6) NOT NULL
  ,ITEMATPSTATUS  VARCHAR(1) NOT NULL
  ,OPITEMPOS      VARCHAR(30)
  ,QUANTITY       INTEGER  NOT NULL
  ,QUANTITYUNIT   VARCHAR(2) NOT NULL
  ,DELIVERYDATE   DATE  NOT NULL
);

CREATE OR REPLACE TABLE SalesOrders(
   SALESORDERID      INTEGER  NOT NULL PRIMARY KEY 
  ,CREATEDBY         INTEGER  NOT NULL
  ,CREATEDAT         DATE  NOT NULL
  ,CHANGEDBY         INTEGER  NOT NULL
  ,CHANGEDAT         DATE  NOT NULL
  ,FISCALYEARVARIANT VARCHAR(2) NOT NULL
  ,FISCALYEARPERIOD  INTEGER  NOT NULL
  ,NOTEID            VARCHAR(30)
  ,PARTNERID         INTEGER  NOT NULL
  ,SALESORG          VARCHAR(4) NOT NULL
  ,CURRENCY          VARCHAR(3) NOT NULL
  ,GROSSAMOUNT       INTEGER  NOT NULL
  ,NETAMOUNT         VARCHAR(9) NOT NULL
  ,TAXAMOUNT         VARCHAR(8) NOT NULL
  ,LIFECYCLESTATUS   VARCHAR(1) NOT NULL
  ,BILLINGSTATUS     VARCHAR(1) NOT NULL
  ,DELIVERYSTATUS    VARCHAR(1) NOT NULL
);