CREATE OR REPLACE TABLE Customer(
   CUSTOMERID     VARCHAR  PRIMARY KEY
  ,CUSTOMERTYPEID VARCHAR 
  ,COUNTRY        VARCHAR 
  ,LANGUAGE       VARCHAR 
  ,CREATEDBY      INTEGER  
  ,CREATEDAT      DATE  
  ,CHANGEDBY      INTEGER  
  ,CHANGEDAT      DATE  
);

CREATE OR REPLACE TABLE CustomersHierarchy(
   HIERARCHYID VARCHAR  PRIMARY KEY
  ,DESCRIPTION VARCHAR 
  ,LEVEL       VARCHAR 
);

CREATE OR REPLACE TABLE CustomerTexts(
   CUSTOMERID   VARCHAR  PRIMARY KEY
  ,LANGUAGE     VARCHAR 
  ,SHORT_DESCR  VARCHAR
  ,MEDIUM_DESCR VARCHAR 
  ,LONG_DESCR   VARCHAR
);

CREATE OR REPLACE TABLE CustomerType(
   CUSTOMERTYPEID VARCHAR  PRIMARY KEY
  ,LANGUAGE       VARCHAR 
  ,CREATEDBY      INTEGER  
  ,CREATEDAT      DATE  
  ,CHANGEDBY      INTEGER  
  ,CHANGEDAT      DATE  
);

CREATE OR REPLACE TABLE CustomerTypeTexts(
   CUSTOMERTYPEID VARCHAR  PRIMARY KEY
  ,LANGUAGE       VARCHAR 
  ,SHORT_DESCR    VARCHAR 
  ,MEDIUM_DESCR   VARCHAR 
  ,LONG_DESCR     VARCHAR
);

CREATE OR REPLACE TABLE FinancialTransactions(
   TRANSACTIONID     INTEGER   PRIMARY KEY 
  ,ACCOUNTID         VARCHAR 
  ,ACCOUNTTYPEID     VARCHAR 
  ,CUSTOMERID        VARCHAR 
  ,CUSTOMERTYPEID    VARCHAR 
  ,PRODUCTID         VARCHAR 
  ,PRODUCTCATEGORYID VARCHAR 
  ,PROFITCENTERID    VARCHAR 
  ,VERSION           VARCHAR 
  ,DATE              DATE  
  ,VALUE             VARCHAR 
);

CREATE OR REPLACE TABLE GLAccounts(
   ACCOUNTID     VARCHAR  PRIMARY KEY
  ,ACCOUNTTYPEID VARCHAR 
  ,LANGUAGE      VARCHAR 
  ,CREATEDBY     INTEGER  
  ,CREATEDAT     DATE  
  ,CHANGEDBY     INTEGER  
  ,CHANGEDAT     DATE  
);

CREATE OR REPLACE TABLE GLAccountsHierarchy(
   HIERARCHYID VARCHAR  PRIMARY KEY
  ,DESCRIPTION VARCHAR 
  ,LEVEL       VARCHAR 
);

CREATE OR REPLACE TABLE GLAccountsTexts(
   ACCOUNTID    VARCHAR  PRIMARY KEY
  ,LANGUAGE     VARCHAR 
  ,SHORT_DESCR  VARCHAR
  ,MEDIUM_DESCR VARCHAR 
  ,LONG_DESCR   VARCHAR
);

CREATE OR REPLACE TABLE GLAccountType(
   ACCOUNTTYPEID VARCHAR  PRIMARY KEY
  ,LANGUAGE      VARCHAR 
  ,CREATEDBY     INTEGER  
  ,CREATEDAT     DATE  
  ,CHANGEDBY     INTEGER  
  ,CHANGEDAT     DATE  
);

CREATE OR REPLACE TABLE GLAccountTypeTexts(
   ACCOUNTTYPEID VARCHAR  PRIMARY KEY
  ,LANGUAGE      VARCHAR 
  ,SHORT_DESCR   VARCHAR
  ,MEDIUM_DESCR  VARCHAR 
  ,LONG_DESCR    VARCHAR
);

CREATE OR REPLACE TABLE ProductCategories(
   PRODCATEGORYID VARCHAR  PRIMARY KEY
  ,LANGUAGE       VARCHAR 
  ,CREATEDBY      INTEGER  
  ,CREATEDAT      DATE  
  ,CHANGEDBY      INTEGER  
  ,CHANGEDAT      DATE  
);

CREATE OR REPLACE TABLE ProductCategoryTexts(
   PRODCATEGORYID VARCHAR  PRIMARY KEY
  ,LANGUAGE       VARCHAR 
  ,SHORT_DESCR    VARCHAR 
  ,MEDIUM_DESCR   VARCHAR
  ,LONG_DESCR     VARCHAR
);

CREATE OR REPLACE TABLE ProductHierarchy(
   HIERARCHYID VARCHAR  PRIMARY KEY
  ,DESCRIPTION VARCHAR 
  ,LEVEL       VARCHAR 
);

CREATE OR REPLACE TABLE Products(
   PRODUCTID          VARCHAR  PRIMARY KEY
  ,TYPECODE           VARCHAR 
  ,PRODUCTCATEGORYID  VARCHAR 
  ,LANGUAGE           VARCHAR 
  ,SUPPLIER_PARTNERID INTEGER  
  ,TAXTARIFFCODE      BOOLEAN  
  ,QUANTITYUNIT       VARCHAR 
  ,WEIGHTMEASURE      INTEGER  
  ,WEIGHTUNIT         VARCHAR 
  ,CURRENCY           VARCHAR 
  ,PRICE              NUMERIC(7,2) 
  ,WIDTH              NUMERIC(5,3) 
  ,DEPTH              NUMERIC(5,3) 
  ,HEIGHT             NUMERIC(5,3) 
  ,DIMENSIONUNIT      VARCHAR
  ,CREATEDBY          INTEGER  
  ,CREATEDAT          DATE  
  ,CHANGEDBY          INTEGER  
  ,CHANGEDAT          DATE  
  ,PRODUCTPICURL      VARCHAR
);

CREATE OR REPLACE TABLE ProductTexts(
   PRODUCTID    VARCHAR  PRIMARY KEY
  ,LANGUAGE     VARCHAR 
  ,SHORT_DESCR  VARCHAR 
  ,MEDIUM_DESCR VARCHAR 
  ,LONG_DESCR   VARCHAR
);

CREATE OR REPLACE TABLE ProfitCenter(
   PROFITCENTERID VARCHAR  PRIMARY KEY
  ,LANGUAGE       VARCHAR 
  ,CREATEDBY      INTEGER  
  ,CREATEDAT      DATE  
  ,CHANGEDBY      INTEGER  
  ,CHANGEDAT      DATE  
);

CREATE OR REPLACE TABLE ProfitCenterHierarchy(
   HIERARCHYID VARCHAR  PRIMARY KEY
  ,DESCRIPTION VARCHAR 
  ,LEVEL       VARCHAR 
);

CREATE OR REPLACE TABLE ProfitCenterTexts(
   PROFITCENTERID VARCHAR  PRIMARY KEY
  ,LANGUAGE       VARCHAR 
  ,SHORT_DESCR    VARCHAR 
  ,MEDIUM_DESCR   VARCHAR 
  ,LONG_DESCR     VARCHAR 
);
