CREATE OR REPLACE TABLE BusinessPartners(
   PARTNERID    INTEGER   PRIMARY KEY 
  ,PARTNERROLE  INTEGER  
  ,EMAILADDRESS VARCHAR(39) 
  ,PHONENUMBER  INTEGER  
  ,FAXNUMBER    VARCHAR(30)
  ,WEBADDRESS   VARCHAR(35) 
  ,ADDRESSID    INTEGER  
  ,COMPANYNAME  VARCHAR(21) 
  ,LEGALFORM    VARCHAR(8) 
  ,CREATEDBY    INTEGER  
  ,CREATEDAT    DATE  
  ,CHANGEDBY    INTEGER  
  ,CHANGEDAT    DATE  
  ,CURRENCY     VARCHAR(3) 
);

CREATE OR REPLACE TABLE SalesOrderItems(
   SALESORDERID   INTEGER   PRIMARY KEY 
  ,SALESORDERITEM INTEGER  
  ,PRODUCTID      VARCHAR(10) 
  ,NOTEID         VARCHAR(30)
  ,CURRENCY       VARCHAR(3) 
  ,GROSSAMOUNT    INTEGER  
  ,NETAMOUNT      VARCHAR(7) 
  ,TAXAMOUNT      VARCHAR(6) 
  ,ITEMATPSTATUS  VARCHAR(1) 
  ,OPITEMPOS      VARCHAR(30)
  ,QUANTITY       INTEGER  
  ,QUANTITYUNIT   VARCHAR(2) 
  ,DELIVERYDATE   DATE  
);

CREATE OR REPLACE TABLE SalesOrders(
   SALESORDERID      INTEGER   PRIMARY KEY 
  ,CREATEDBY         INTEGER  
  ,CREATEDAT         DATE  
  ,CHANGEDBY         INTEGER  
  ,CHANGEDAT         DATE  
  ,FISCALYEARVARIANT VARCHAR(2) 
  ,FISCALYEARPERIOD  INTEGER  
  ,NOTEID            VARCHAR(30)
  ,PARTNERID         INTEGER  
  ,SALESORG          VARCHAR(4) 
  ,CURRENCY          VARCHAR(3) 
  ,GROSSAMOUNT       INTEGER  
  ,NETAMOUNT         VARCHAR(9) 
  ,TAXAMOUNT         VARCHAR(8) 
  ,LIFECYCLESTATUS   VARCHAR(1) 
  ,BILLINGSTATUS     VARCHAR(1) 
  ,DELIVERYSTATUS    VARCHAR(1) 
);