USE DATABASE FI;

CREATE TABLE Customer(
   CUSTOMERID     VARCHAR(10) NOT NULL PRIMARY KEY
  ,CUSTOMERTYPEID VARCHAR(2) NOT NULL
  ,COUNTRY        VARCHAR(2) NOT NULL
  ,LANGUAGE       VARCHAR(2) NOT NULL
  ,CREATEDBY      INTEGER  NOT NULL
  ,CREATEDAT      DATE  NOT NULL
  ,CHANGEDBY      INTEGER  NOT NULL
  ,CHANGEDAT      DATE  NOT NULL
);

CREATE TABLE CustomersHierarchy(
   HIERARCHYID VARCHAR(10) NOT NULL PRIMARY KEY
  ,DESCRIPTION VARCHAR(22) NOT NULL
  ,LEVEL       VARCHAR(6) NOT NULL
);

CREATE TABLE CustomerTexts(
   CUSTOMERID   VARCHAR(10) NOT NULL PRIMARY KEY
  ,LANGUAGE     VARCHAR(2) NOT NULL
  ,SHORT_DESCR  VARCHAR(30)
  ,MEDIUM_DESCR VARCHAR(22) NOT NULL
  ,LONG_DESCR   VARCHAR(30)
);

