CREATE TABLE Departments(
   DEPARTMENTID VARCHAR  PRIMARY KEY
  ,LANGUAGE     VARCHAR 
  ,CREATEDBY    INTEGER  
  ,CREATEDAT    DATE  
);

CREATE TABLE DepartmentTexts(
   DEPARTMENTID       VARCHAR  PRIMARY KEY
  ,LANGUAGE           VARCHAR 
  ,SHORT_DESCRIPTION  VARCHAR 
  ,MEDIUM_DESCRIPTION VARCHAR
  ,LONG_DESCRIPTION   VARCHAR
);

CREATE TABLE Divisions(
   DIVISIONID VARCHAR  PRIMARY KEY
  ,LANGUAGE   VARCHAR 
  ,CREATEDBY  INTEGER  
  ,CREATEDAT  DATE  
);

CREATE TABLE DivisionTexts(
   DIVISIONID         VARCHAR  PRIMARY KEY
  ,LANGUAGE           VARCHAR 
  ,SHORT_DESCRIPTION  VARCHAR 
  ,MEDIUM_DESCRIPTION VARCHAR
  ,LONG_DESCRIPTION   VARCHAR
);

CREATE TABLE EmployeeHeadcount(
   EMPLOYEEID          VARCHAR  PRIMARY KEY
  ,DIVISIONID          VARCHAR 
  ,DEPARTMENTID        VARCHAR 
  ,JOBID               INTEGER  
  ,JOBCLASSIFICATIONID VARCHAR 
  ,MANAGERID           VARCHAR 
  ,EXITREASON          VARCHAR 
  ,DATE                DATE  
  ,EXITDATE            DATE  
  ,FTE                 BOOLEAN  
  ,STANDARDWEEKLYHOURS INTEGER  
  ,WORKINGDAYSPERWEEK  INTEGER  
  ,SALARY              INTEGER  
);

CREATE TABLE EmployeePerformance(
   EMPLOYEEID   VARCHAR  PRIMARY KEY
  ,PERFORMANCE  VARCHAR 
  ,IMPACTOFLOSS VARCHAR 
  ,FUTURELEADER VARCHAR 
);

CREATE TABLE EmployeePersonalData(
   EMPLOYEEID    VARCHAR  PRIMARY KEY
  ,FIRSTNAME     VARCHAR 
  ,LASTNAME      VARCHAR 
  ,FULLNAME      VARCHAR 
  ,GENDER        VARCHAR 
  ,MARITALSTATUS VARCHAR 
  ,ETHNICITY     VARCHAR 
  ,YEAROFBIRTH   INTEGER  
  ,LOCATIONID    VARCHAR 
);

CREATE TABLE EmployeePosition(
   EMPLOYEEID    VARCHAR  PRIMARY KEY
  ,JOBID         INTEGER  
  ,NEWTOPOSITION VARCHAR 
  ,PAYGRADEID    VARCHAR 
  ,FULLTIME      VARCHAR 
  ,COMPANYCODE   VARCHAR 
  ,BUSINESSAREA  VARCHAR 
);

CREATE TABLE HRManager(
   MANAGERID VARCHAR  PRIMARY KEY
  ,FIRSTNAME VARCHAR 
  ,LASTNAME  VARCHAR 
  ,FULLNAME  VARCHAR 
);

CREATE TABLE Job(
   JOBID               INTEGER   PRIMARY KEY 
  ,JOBCLASSIFICATIONID VARCHAR 
  ,LANGUAGE            VARCHAR 
  ,CREATEDBY           INTEGER  
  ,CREATEDAT           DATE  
);

CREATE TABLE JobClassification(
   JOBCLASSIFICATIONID VARCHAR  PRIMARY KEY
  ,LANGUAGE            VARCHAR 
  ,CREATEDBY           INTEGER 
  ,CREATEDAT           DATE  
);

CREATE TABLE JobClassificationTexts(
   JOBCLASSIFICATIONID VARCHAR  PRIMARY KEY
  ,LANGUAGE            VARCHAR 
  ,SHORT_DESCRIPTION   VARCHAR 
  ,MEDIUM_DESCRIPTION  VARCHAR
  ,LONG_DESCRIPTION    VARCHAR
);

CREATE TABLE JobTexts(
   JOBCLASSIFICATIONID VARCHAR  PRIMARY KEY
  ,LANGUAGE            VARCHAR 
  ,SHORT_DESCRIPTION   VARCHAR 
  ,MEDIUM_DESCRIPTION  VARCHAR
  ,LONG_DESCRIPTION    VARCHAR
);

CREATE TABLE Location(
   LOCATIONID VARCHAR  PRIMARY KEY
  ,LANGUAGE   VARCHAR 
  ,CREATEDBY  INTEGER  
  ,CREATEDAT  DATE  
);

CREATE TABLE LocationHierarchy(
   HIERARCHYID VARCHAR  PRIMARY KEY
  ,DESCRIPTION VARCHAR 
  ,LEVEL       VARCHAR 
);

CREATE TABLE LocationTexts(
   LOCATIONID         VARCHAR  PRIMARY KEY
  ,LANGUAGE           VARCHAR 
  ,SHORT_DESCRIPTION  VARCHAR 
  ,MEDIUM_DESCRIPTION VARCHAR 
  ,LONG_DESCRIPTION   VARCHAR
);
